USE retail_sales_project;
# Task 3: Business Questions

#1.The manager wants to see the 5 largest individual sales, showing the customer, product, city, and amount.

SELECT customer,product,city,amount
FROM sales
ORDER BY amount DESC
LIMIT 5;

#2. Find all sales made by Thabo in Johannesburg.

SELECT*
FROM sales
WHERE customer="Thabo" AND city="Johannesburg";

#3. Which customers have made more than 2 purchases?

SELECT customer,COUNT(amount) AS purchases
FROM sales
GROUP BY customer
HAVING purchases > 2;



#4. Which products have been sold in more than one city?

SELECT product,COUNT(DISTINCT city) AS count_city
FROM sales
GROUP BY  product
HAVING count_city >1
;

SELECT*
FROM sales;

#5. Show the total revenue generated by each customer, but only include customers whose total spending is above R10,000.

SELECT customer,SUM(amount) AS total_revenue
FROM sales
GROUP BY customer
HAVING total_revenue > 10000
;

#6. The manager wants to see all Electronics sales where the amount was greater than R5,000, with the newest sales appearing first.

SELECT category,amount,sale_date
FROM sales
WHERE category ="Electronics" AND amount >5000
ORDER BY sale_date DESC;


#7. Find the 3 products with the highest total quantity sold.

SELECT product,SUM(quantity) AS 'total_quantity_sold'
FROM sales
GROUP BY product
ORDER BY total_quantity_sold DESC
LIMIT 3 ;

#8. Show each city and its average sale amount, but only include cities where the average sale is above R4,000.

SELECT city,AVG(amount) AS 'average_sale_amount'
FROM sales
GROUP BY city
HAVING average_sale_amount > 4000
;

#9. Find customers whose names contain the letter "a".

SELECT customer
FROM sales
WHERE customer LIKE "%a%";



#10. The manager wants a list of all unique customer names, arranged alphabetically.


SELECT DISTINCT customer
FROM sales
ORDER BY customer;




